#!/usr/bin/env bash
#Server details:
#server="34.138.32.248"
#private_key="~/.ssh/school"
#username="ubuntu"
# Connects to server 34.138.32.248 with key in ~/.ssh/school

ssh -i ~/.ssh/school ubuntu@34.138.32.248
